package com.rudearts.weatherapp.model.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.rudearts.weatherapp.model.greendao.CityDb;
import com.rudearts.weatherapp.model.greendao.WeatherDb;

import com.rudearts.weatherapp.model.greendao.CityDbDao;
import com.rudearts.weatherapp.model.greendao.WeatherDbDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig cityDbDaoConfig;
    private final DaoConfig weatherDbDaoConfig;

    private final CityDbDao cityDbDao;
    private final WeatherDbDao weatherDbDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        cityDbDaoConfig = daoConfigMap.get(CityDbDao.class).clone();
        cityDbDaoConfig.initIdentityScope(type);

        weatherDbDaoConfig = daoConfigMap.get(WeatherDbDao.class).clone();
        weatherDbDaoConfig.initIdentityScope(type);

        cityDbDao = new CityDbDao(cityDbDaoConfig, this);
        weatherDbDao = new WeatherDbDao(weatherDbDaoConfig, this);

        registerDao(CityDb.class, cityDbDao);
        registerDao(WeatherDb.class, weatherDbDao);
    }
    
    public void clear() {
        cityDbDaoConfig.clearIdentityScope();
        weatherDbDaoConfig.clearIdentityScope();
    }

    public CityDbDao getCityDbDao() {
        return cityDbDao;
    }

    public WeatherDbDao getWeatherDbDao() {
        return weatherDbDao;
    }

}
