package com.rudearts.weatherapp.model.greendao;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "WEATHER_DB".
 */
@Entity
public class WeatherDb {

    @Id
    private Long id;
    private Integer cod;
    private Integer main;
    private Integer description;
    private Integer icon;
    private Double temperature;
    private Double pressure;
    private Double humidity;

    @Generated
    public WeatherDb() {
    }

    public WeatherDb(Long id) {
        this.id = id;
    }

    @Generated
    public WeatherDb(Long id, Integer cod, Integer main, Integer description, Integer icon, Double temperature, Double pressure, Double humidity) {
        this.id = id;
        this.cod = cod;
        this.main = main;
        this.description = description;
        this.icon = icon;
        this.temperature = temperature;
        this.pressure = pressure;
        this.humidity = humidity;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getCod() {
        return cod;
    }

    public void setCod(Integer cod) {
        this.cod = cod;
    }

    public Integer getMain() {
        return main;
    }

    public void setMain(Integer main) {
        this.main = main;
    }

    public Integer getDescription() {
        return description;
    }

    public void setDescription(Integer description) {
        this.description = description;
    }

    public Integer getIcon() {
        return icon;
    }

    public void setIcon(Integer icon) {
        this.icon = icon;
    }

    public Double getTemperature() {
        return temperature;
    }

    public void setTemperature(Double temperature) {
        this.temperature = temperature;
    }

    public Double getPressure() {
        return pressure;
    }

    public void setPressure(Double pressure) {
        this.pressure = pressure;
    }

    public Double getHumidity() {
        return humidity;
    }

    public void setHumidity(Double humidity) {
        this.humidity = humidity;
    }

}
